/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package UserRegistrationSystem;

import org.junit.Test;
import static org.junit.Assert.*;

public class UserRegistrationTest {
    @Test public void validateName_ValidName_True() {
        UserRegistration userRegistration = new UserRegistration();
        assertTrue(userRegistration.validateName("Zoya"));
    }
    @Test public void validateName_ValidName_False() {
        UserRegistration userRegistration = new UserRegistration();
        assertFalse(userRegistration.validateName("zoya"));
    }
    @Test public void validateEmail_ValidEmail_True() {
        UserRegistration userRegistration = new UserRegistration();
        assertTrue(userRegistration.validateEmail("abc@yahoo.com"));
    }
    @Test public void validateEmail_ValidEmail_False() {
        UserRegistration userRegistration = new UserRegistration();
        assertFalse(userRegistration.validateEmail("1ds@hsj.com"));
    }	
    @Test public void validatePhone_ValidPhone_True() {
        UserRegistration userRegistration = new UserRegistration();
        assertTrue(userRegistration.validatePhone("91 1234567890"));
    }
    @Test public void validateEmail_ValidPhone_False() {
        UserRegistration userRegistration = new UserRegistration();
        assertFalse(userRegistration.validatePhone("1234 90191"));
    }
}
