/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package UserRegistrationSystem;

import org.junit.Test;
import static org.junit.Assert.*;

public class UserRegistrationTest {
    @Test public void testSomeLibraryMethod() {
        UserRegistration classUnderTest = new UserRegistration();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
