/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package UserRegistrationSystem;

import java.util.regex.Pattern;

public class UserRegistration {
	public boolean validateName(String name) {
		String nameValidation="^[A-Z][a-z]{2,}$";
		return Pattern.matches(nameValidation, name);
	}
	
	public static boolean validateEmail(String email) {
		String emailValidation="^[a-zA-Z]{1,}[\\.\\_\\-\\+]?[a-zA-Z0-9]*[@]{1}[a-z0-9]+[.]{1}[a-z]+[.]?[a-z]{2}$";
		return Pattern.matches(emailValidation,email);
	}
	
	public static boolean validatePhone(String phoneNumber) {
		String phoneValidation="^[0-9]{2,3}\\s[0-9]{10}$";
		return Pattern.matches(phoneValidation,phoneNumber);
	}
	
	public static boolean validatePassword(String password) {
		String passwordValidation="^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=]).{8,}$";
		return Pattern.matches(passwordValidation,password);
	}
}
