/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package UserRegistrationSystem;

import java.util.regex.Pattern;

public class UserRegistration {
	public boolean validateName(String name) {
		String nameValidation="^[A-Z][a-z]{2,}$";
		return Pattern.matches(nameValidation, name);
	}
	
	public static boolean validateEmail(String email) {
		String emailValidation="^[a-zA-Z]{1,}[\\.\\_\\-\\+]?[a-zA-Z0-9]*[@]{1}[a-z0-9]+[.]{1}[a-z]+[.]?[a-z]{2}$";
		return Pattern.matches(emailValidation,email);
	}
}
